server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    location / {
        return 503;
    }
    location ~ ^/(logo-negro.png|error.svg|favicon.ico|config/message.json)$ {
    }
    error_page  500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
