name: Redfid Docker Image CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'redfid'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
    paths:
      - 'redfid'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Build RedFID
        run: docker build ./redfid --file ./redfid/Dockerfile --tag ghcr.io/eol-uchile/not-available-container:redfid-${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: (github.ref == 'refs/heads/main')
        run: |
          docker push ghcr.io/eol-uchile/not-available-container:redfid-${GITHUB_SHA}
