name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Virtual labx
        run: docker build ./virtuallabx --file ./virtuallabx/Dockerfile --tag ghcr.io/eol-uchile/not-available-container:virtuallabx-${GITHUB_SHA}

      - name: Build Norteamericano
        run: docker build ./norteamericano --file ./norteamericano/Dockerfile --tag ghcr.io/eol-uchile/not-available-container:norteamericano-${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        run: |
          docker push ghcr.io/eol-uchile/not-available-container:virtuallabx-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/not-available-container:norteamericano-${GITHUB_SHA}
